kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: ci-helper-app
  name: ci-helper-app
spec:
  selector:
    matchLabels:
      app: ci-helper-app
  replicas: 1
  template:
    metadata:
      labels:
        app: ci-helper-app
    spec:
      restartPolicy: Always
      containers:
        - image: quay.io/konflux-ci/ci-helper-app:v0.1
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          name: ci-helper-app
          command: ["/ci-helper-app"]
          resources:
            requests:
              cpu: "10m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
          env:
            - name: GITHUB_APP_INTEGRATION_ID
              valueFrom:
                secretKeyRef:
                  name: ci-helper-app-secrets
                  key: app-id
            - name: GITHUB_APP_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: ci-helper-app-secrets
                  key: webhook-secret
            - name: GITHUB_APP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: ci-helper-app-secrets
                  key: app-private-key
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP